services:
  ccu-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccu-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      MIN_RAM: 8G
      MAX_RAM: 8G
      SERVER_DIR: /data
      BOOTSTRAP_DIR: /bootstrap
      MODPACK_ARCHIVE: /bootstrap/modpack.zip
      MODS_ARCHIVE: /bootstrap/mods.zip
      MODPACK_URL: ""
      JAVA_OPTS: ""
    volumes:
      - ./:/data
      - ./bootstrap:/bootstrap
